language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

# Cache dependencies in $HOME/.yarn-cache across builds
cache: yarn

# Run the the validate script with code coverage
script: yarn run validate -- -- --coverage

# Scripts to run after validation tests run
after_success:
  # Install coveralls globally
  - yarn global add coveralls semantic-release

  # Retrieve the coverage information and send it to Coveralls
  - cat ./coverage/lcov.info | coveralls

  # 0. Build lib files
  # 1. Update package.json version number based on commits
  # 2. Publish new version to NPM
  # 3. Generate changelog + release on Github
  - yarn run build
  - semantic-release pre && npm publish && semantic-release post

# Build web bundle
# before_deploy: yarn run bundle

# Publish to NPM
# deploy:
#   skip_cleanup: true
#   provider: script
#   script:  ./_scripts/travis-deploy.sh
#   on:
#     branch: master
#     node: "node"
