language: node_js
node_js:
  - "node"
  - "7"
  - "6"

# Cache dependencies in $HOME/.yarn-cache across builds
cache: yarn

# Run the the validate script with code coverage
script: yarn run validate -- -- --coverage

# Send coverage data to Coveralls
after_success:
  - yarn global add coveralls
  - cat ./coverage/lcov.info | coveralls

# Only run CI on master branch
branches:
  only:
    - master

# Build dist files
# before_deploy: yarn run bundle:web

# Deploy to gh-pages branch on Github
# deploy:
#   skip_cleanup: true
#   provider: script
#   script:  ./_scripts/travis-deploy.sh
#   on:
#     branch: master
#     node: "node"
